name: splunk-github-sbom
description: Send your SBOM data to a Splunk instance via the HTTP Event Collector endpoint.
author: James Hodgkinson <james@terminaloutcomes.com>
inputs:
  github_token:
    description: 'The GitHub token to use'
    required: true
  server:
    description: 'The Splunk server to send to'
    required: true
  splunk_token:
    description: 'The HEC token to use'
    required: true
  index:
    description: 'Set the index'
    required: false
  sourcetype:
    description: 'Set the sourcetype'
    default: 'github:sbom'
    required: false
  source:
    description: 'Set the source'
    default: 'github-actions'
    required: false
  port:
    description: 'Set the HEC port'
    default: "8088"
    required: false
  repository:
    description: "The full repo name, ie 'yaleman/hello-world'"
    required: false
outputs:
  error:
    description: 'The description of any error that occurred'
runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.server }}
    - ${{ inputs.token }}
    - ${{ inputs.data }}
    - ${{ inputs.index }}
    - ${{ inputs.sourcetype }}
    - ${{ inputs.source }}

