[package]
name = "splunk-github-sbom"
description = "Send your SBOM data to a Splunk instance via the HTTP Event Collector endpoint."
version = "0.1.1"
edition = "2021"
rust-version = "1.67"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
serde_json = "1.0.143"
reqwest = { version = "0.12.23", features = ["json"] }

splunk = { version = "0.1.2" }
tokio = { version = "1.47.1", features = ["rt", "macros"] }

[dev-dependencies]
regex = "1.11.1"
serde_yaml = "0.9.34"
