[package]
name = "splunk-github-sbom"
description = "Send your SBOM data to a Splunk instance via the HTTP Event Collector endpoint."
version = "0.1.1"
edition = "2021"
rust-version = "1.67"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
serde_json = "1.0.149"
reqwest = { version = "0.13.2", features = ["json"] }

splunk = { version = "0.1.3" }
tokio = { version = "1.52.1", features = ["rt", "macros"] }

[dev-dependencies]
regex = "1.12.3"
serde_yaml = "0.9.34"
