name: Unit tests, linting, and formatting
"on":
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: |
          rustup override set stable
          rustup update stable
      - name: Run tests
        run: cargo test
      - name: Lint
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check