---
"on":
  push:
  pull_request:

jobs:
  test_thyself:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: yaleman/splunk-github-sbom@dev
        with:
          github_token: "${{ github.token }}"
          server: "${{ secrets.SERVER }}server"
          port: "${{ secrets.PORT }}port"
          splunk_token: "${{ secrets.TOKEN }}token"
          repository: "${{ github.repository }}repository"
