---
"on":
  push:
  pull_request:

jobs:
  test_thyself:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yaleman/splunk-github-sbom@dev
        with:
          github_token: ${{ github.token }}
          server: ${{ secrets.SERVER }}
          port: ${{ secrets.PORT }}
          splunk_token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
