---
"on":
  push:
  pull_request:

jobs:
  test_thyself:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yaleman/splunk-github-sbom@dev
        with:
          repository: ${github.repository}
          server: ${{ secrets.SERVER }}
          token: ${{ secrets.TOKEN }}
          port: ${{ secrets.PORT }}
