---
name: Self-test
"on":
  push:
    branches:
      - v1
      - dev
jobs:
  test_thyself:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: yaleman/splunk-github-sbom@dev
        with:
          github_token: "${{ github.token }}"
          server: "${{ secrets.SERVER }}"
          port: "${{ secrets.PORT }}"
          splunk_token: "${{ secrets.TOKEN }}"
          repository: "${{ github.repository }}"
